language: python

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"

before_install:
    - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then pip install --use-mirrors --quiet argparse; fi

install:
    - python setup.py --quiet install

script:
    - ./test_pydiff.py
    - pydiff pydiff pydiff
